#!/usr/bin/env groovy

node('linux' && 'docker') {
  def repo = "wine_test_repo"

  stage('Setup Workspace') {
    deleteDir()
    // Clone source code from Bitbucket
    checkout scm
  }

  def customImage

  stage('Build Image') {
    customImage = docker.build(repo)
  }

  stage('Test Image using shell') {
    sh "docker run -tu root ${repo} wine /usr/wine_test/helloworld.exe"
  }

  stage('Test Image using plugin') {
    customImage.inside("-u root") {
      sh "wine /usr/wine_test/helloworld.exe"
    }
  }

  stage('Cleanup Workspace') {
    deleteDir()
  }
}

// vim: ft=groovy