apiVersion: v1
kind: Pod
spec:
  imagePullSecrets:
    - name: regsecret
  nodeSelector: 
    worktype: hunnyapp
  nodeUsageMode: 'NORMAL'
  containers:
    - name: jnlp
      image: registry.corp.com:5000/corp-digital/digital-jenkins-slave:digital-publicwebsite-latest
      args: ["$(JENKINS_SECRET)", "$(JENKINS_NAME)"]
      tty: true
      workingDir: /home/jenkins
      privileged: true
      resources:
        limits:
          cpu: '1500m'
          memory: '1500Mi'
        requests:
          cpu: '250m'
          memory: '500Mi'
      env:
        - name: JENKINS_URL
          value: http://corpkube:32572/jenkins
        - name: HOME
          value: /home/jenkins
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: splunk
              key: password
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: splunk
              key: username
        - name: JENKINS_TUNNEL
          value: jenkins-agent.jenkins:50000