import java.util.*;
/**
 * Entry point to auto-generated tests (generated by maven-hpi-plugin).
 * If this fails to compile, you are probably using Hudson &lt; 1.327. If so, disable
 * this code generation by configuring maven-hpi-plugin to &lt;disabledTestInjection>false&lt;/disabledTestInjection>.
 */
public class InjectedTest extends junit.framework.TestCase {
  public static junit.framework.Test suite() throws Exception {
    Map parameters = new HashMap();
    parameters.put("basedir","C:\work\Toolbox\Tools\Hudson\StarTeamPlugin");
    parameters.put("artifactId","ztarteamplugin");
    parameters.put("outputDirectory","C:\work\Toolbox\Tools\Hudson\StarTeamPlugin\target\classes");
    parameters.put("testOutputDirectory","C:\work\Toolbox\Tools\Hudson\StarTeamPlugin\target\test-classes");
    return new org.jvnet.hudson.test.PluginAutomaticTestBuilder().build(parameters);
  }
}
