properties([
	parameters(
		[string(name: 'GitCheckout', defaultValue: 'refs/heads/master', description: '') ]
	)
])

node {

	tc_test{
		repo = 'test1'
		folder = 'test2'
		submodules = true
		refs = params.GitCheckout
	}

}